name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    strategy:
      matrix:
        include:
          - os: "ubuntu-latest"
            target: "x86_64-unknown-linux-gnu"
          - os: "windows-latest"
            target: "x86_64-pc-windows-msvc"
          - os: "macos-latest"
            target: "x86_64-apple-darwin"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Rustup
        run: |
          rustup update
          rustup target list
          rustup component add clippy

      - uses: Swatinem/rust-cache@v2

      - name: Cargo Clippy
        run: cargo clippy --all-features --all -- -D warnings

      - name: Run tests
        run: cargo test -v --all-features --all

      - name: Build
        run: cargo build -v --all

      - name: List target
        run: ls -l target/debug

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: |
            target/debug/*yxy*

  check-musl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install musl
        run: sudo apt-get install musl-tools

      - name: Rustup
        run: |
          rustup update
          rustup target add x86_64-unknown-linux-musl
          rustup target list
          rustup component add clippy

      - uses: Swatinem/rust-cache@v2

      - name: Cargo Clippy
        run: cargo clippy --all-features --all --target x86_64-unknown-linux-gnu -- -D warnings

      - name: Run tests
        run: cargo test -v --all-features --all --target x86_64-unknown-linux-gnu

      - name: Build
        run: cargo build -v --all --target x86_64-unknown-linux-gnu

      - name: List target
        run: ls -l target/x86_64-unknown-linux-gnu/debug

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-unknown-linux-gnu 
          path: |
            target/x86_64-unknown-linux-gnu/debug/*yxy*
    
